version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    entrypoint: /bin/sh -c
    command: |
      while true; do
        certbot renew --webroot -w /usr/share/nginx/html --quiet --deploy-hook "nginx -s reload"
        sleep 12h
      done
    restart: always
